name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADDR }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PW }}
          port: 22
          script: |
            ansible-playbook --inventory-file=invetory.ini ~/abdullohAqil/bms-praktik-test/deploy.yml
            curl -i localhost:5758